---
kind: pipeline
name: octant

workspace:
  base: /go
  path: src/github.com/vmware-tanzu/octant

steps:
  - name: fetch
    image: docker:git
    commands:
      - git fetch --tags
  - name: frontend
    image: sfoo/node-chrome:0.0.2
    commands:
      - cd web
      - npm ci
      - npm run-script build
      - npm run lint
      - npm run test:headless
  - name: backend
    image: golang:1.13
    environment:
      GOFLAGS: -mod=vendor
      GO111MODULE: on
    commands:
      - make go-install
      - make test
      - go generate ./web
      - make vet
    depends_on:
    - frontend
  - name: build
    image: golang:1.13
    environment:
      CGO_ENABLED: 0
    commands:
      - make octant-dev
    depends_on:
    - frontend
    - backend
  - name: releaser
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    when:
      event:
        - tag
    image: goreleaser/goreleaser:v0.120-cgo
    commands:
      - ci/drone-deploy.sh
    depends_on:
    - build
  - name: releaser-nightly
    environment:
      GOOGLE_APPLICATION_JSON:
        from_secret: google_application_json
    when:
      cron: [ nightly ]
    image: goreleaser/goreleaser:v0.120-cgo
    commands:
      - echo "$GOOGLE_APPLICATION_JSON" | base64 -d > /tmp/gs.json
      - GOOGLE_APPLICATION_CREDENTIALS=/tmp/gs.json goreleaser -f .goreleaser-nightly.yml --rm-dist --skip-validate
    depends_on:
     - build 
---
kind: signature
hmac: 9540a6d6fc51dceafdff21f9b5ebae279cc0679b55b4c7e3d58f775c20dd84f7

...
