version: 2
jobs:
  build:
    machine:
      enabled: true
      docker_layer_caching: true 
    steps:
    - checkout
    - run:
        name: Build
        command: |
          docker build -t octant-image .
          docker run --name octant-builder octant-image
    - run:
        name: Cluster
        command: |
          wget -O kind https://github.com/kubernetes-sigs/kind/releases/download/v0.4.0/kind-linux-amd64
          chmod +x ./kind
          ./kind create cluster
          echo 'export KUBECONFIG=$(./kind get kubeconfig-path)' >> $BASH_ENV
    - run:
        name: Kubectl
        command: |
          source $BASH_ENV
          wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl
          chmod +x ./kubectl
          ./kubectl apply -f examples/resources/crd-crontab.yaml
          ./kubectl apply -f examples/resources/crd-crontab-resource.yaml
    - run:
        name: Octant
        command: |
          docker cp octant-builder:/octant .
          ./octant version
          ./octant
        environment:
          OCTANT_DISABLE_OPEN_BROWSER: 1
          OCTANT_LISTENER_ADDR: localhost:7777
        background: true
    - run:
        name: Cypress
        command: |
          cd web && npm install
          ./node_modules/.bin/cypress run 
        environment:
          CYPRESS_baseUrl: http://localhost:7777
